language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
    - cp -R $ANDROID_HOME/extras/android/m2repository/ ~/.m2/repository/

install: mvn clean install

script: mvn checkstyle:checkstyle

